# Generated by Django 4.0.6 on 2022-12-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safia', '0003_suggestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=56, null=True),
        ),
    ]
